# Generated by Django 5.1.2 on 2025-06-05 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField()),
                ('thumbnail', models.URLField()),
                ('genre', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_currently_watching', models.BooleanField(default=False)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], max_length=10)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('personal_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tmdb_id', 'media_type')},
            },
        ),
    ]
